apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-air-config
  namespace: sample-app-namespace-1762804253756
  labels:
    app.kubernetes.io/name: contoso-air
    kubernetes.azure.com/generator: devhub
data: